name: Deploy Backend WhatsApp

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build e push da imagem
        run: |
          docker build -t devnardi/back-whatsapp:latest .
          docker push devnardi/back-whatsapp:latest

      - name: Subindo novo container com variáveis
        run: |
          docker rm -f back-whatsapp || true
          docker pull devnardi/back-whatsapp:latest
          docker run -d --name back-whatsapp -p 4040:4000 \
            -e DATABASE_URL="${{ secrets.DATABASE_URL_WHATS }}" \
            -e CORS="https://renannardi.com" \
            -e CHROME_PATH="/usr/bin/chromium-browser" \
            devnardi/back-whatsapp:latest

