name: Deploy Backend Prefeitura

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Build e push da imagem
        run: |
          docker build -t devnardi/example:latest .
          docker push devnardi/example:latest

      - name: Subindo novo container com variáveis
        run: |
            docker rm -f example || true
            docker pull devnardi/example:latest
            docker run -d \
            --name example \
            -p 4000:4000 \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e JWT_ACCESS_SECRET="${{ secrets.JWT_ACCESS_SECRET }}" \
            -e CORS="https://example.com,http://localhost:3000" \
            devnardi/example:latest
